### PR TITLE
Remove the img sprite since it's not used.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by clrux** [comment]
@XhmikosR Would you mind squashing these down into a single commit, please?

**Comment by XhmikosR** [comment]
Done.

**Comment by XhmikosR** [comment]
Hmm, so apparently the sprite is still being referenced in the CSS. Will you clean that up yourself @clrux ?

**Comment by clrux** [comment]
I'm actually working on a version two. So let's close this one as it won't apply to the new version.

**Pull request closed without merging**
